// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  video_slice: dynamic(() => import("./VideoSlice")),
};
