// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  highlighted_text: dynamic(() => import("./HighlightedText")),
  projects: dynamic(() => import("./Projects")),
  video_slice: dynamic(() => import("./VideoSlice")),
};
