import { GeistSans } from 'geist/font/sans';
import { League_Spartan } from 'next/font/google';
import LenisInstantiator from '@/components/LenisInstantiator';
import './globals.css';

const leagueSpartan = League_Spartan({
  weight: ['100', '400', '600', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <LenisInstantiator>
        <body className={GeistSans.className}>
          {/* <Navbar /> */}
          {children}
        </body>
      </LenisInstantiator>
    </html>
  );
}
